csmrd-init: added debug logs for /dev/nbd6 config partition
Change-Id: I297f802bbeefe6dc86df012e4008b3d22555e205

diff --git a/recipes-products/images/include/csmrd-init b/recipes-products/images/include/csmrd-init
--- a/recipes-products/images/include/csmrd-init
+++ b/recipes-products/images/include/csmrd-init
@@ -572,6 +572,7 @@ do_nbdtab()
 {
     portno="$2"
     config_portno="$3"
+    local timeout=300
     # Create nbd-server config
     echo "nbd0 $1 system.img.raw persist" > /etc/nbdtab
     echo "nbd1 $1 systemrw.img.raw  persist" >> /etc/nbdtab
@@ -592,6 +593,8 @@ do_nbdtab()
 
     if [ $config_portno != "0" ]; then
         nbdclient nbd6 $config_portno # connect Modem config files
+        nst=$?
+        echo "nbdclient nbd6 status: $nst"
     fi
     nbdclient nbd7 $portno # connect manifest.bin
 
@@ -616,13 +619,26 @@ do_nbdtab()
         echo "mkdir status: $st"
         if [ $st -eq 0 ]; then
         while [ ! -d "$mnt_hostmgr_dir" ] || [ ! -b "/dev/nbd6p1" ]; do
-            sleep 1
             echo "sleeping until dir and /dev/nbd6p1 available. "
+            if [ $nst -ne 0 ]; then
+                nbdclient nbd6 $config_portno # connect Modem config files
+                nst=$?
+            fi
+            echo "nbdclient2 nbd6 status: $nst"
+            if [ "$timeout" -le 0 ]; then
+                echo "nbdclient for nbd6 failed with timeout"
+                break
+            fi
+            sleep 2
+            timeout=$((timeout - 2))
         done
         fi
         mount /dev/nbd6p1 $mnt_hostmgr_dir
         st=$?
         echo "nbd6 mount status $st"
+        if [ $st -ne 0 ]; then
+            echo "Failed to mount nbd6p1 to $mnt_hostmgr_dir"
+        fi
         mount | grep nbd6
     fi
 
